notification:
    - telegrambot1

telegrambot1:
    type: telegram
    token:
    chat_id:
        -
    parse_mode: HTML
    disable_web_page_preview: false
    disable_notification: false
    protect_content: false
    template: template/telegram/HTML # if not set, use built-in template
